---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://srv.siworks.org/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: c3lul4rM4ld1to

    - name: Delete VMs
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: OvirtCL
        template: RHEL7
        name: "{{ item }}"
        state: absent
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        cloud_init:
          host_name: "{{ item }}"
          user_name: root
          root_password: password
          nic_name: eth0
          nic_on_boot: true
          nic_boot_protocol: dhcp

          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ item }}
              - yum -y remove cloud-init
        wait: true
      with_items:
         - vini001
    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
