---

- name: deploy reverse proxy configurations
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx_reverse_proxy_config_directory }}/{{ item.config_name }}.conf"
  with_items: "{{ nginx_reverse_proxy_proxies }}"
  notify:
    - restart nginx
